# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Oracle implementations of JREs, JDKs, and Native Image"
  homepage = "https://github.com/paketo-buildpacks/oracle"
  id = "paketo-buildpacks/oracle"
  keywords = ["java", "jvm", "jre", "jdk", "native-image"]
  name = "Paketo Buildpack for Oracle"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/oracle/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.6:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Oracle JDK"
    purl = "pkg:generic/oracle-jdk@21.0.6?arch=amd64"
    sha256 = "e6a8125085949cb6c9fb823c79ed009a0ef24c878662c02fcb5ae890375e5a38"
    stacks = ["*"]
    uri = "https://download.oracle.com/java/21/archive/jdk-21.0.6_linux-x64_bin.tar.gz"
    version = "21.0.6"

    [[metadata.dependencies.licenses]]
      type = "Oracle No-Fee Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/no-fee-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:23.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Oracle JDK"
    purl = "pkg:generic/oracle-jdk@23.0.2?arch=amd64"
    sha256 = "12d7553d06b5cacf88b26cad4a8ba83cabe79646f1defb1b7fd029f3356d0922"
    stacks = ["*"]
    uri = "https://download.oracle.com/java/23/archive/jdk-23.0.2_linux-x64_bin.tar.gz"
    version = "23.0.2"

    [[metadata.dependencies.licenses]]
      type = "Oracle No-Fee Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/no-fee-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.5:*:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "Oracle GraalVM"
    purl = "pkg:generic/graalvm-jdk@21.0.5?arch=amd64"
    sha256 = "c1960d4f9d278458bde1cd15115ac2f0b3240cb427d51cfeceb79dab91a7f5c9"
    stacks = ["*"]
    uri = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.5_linux-x64_bin.tar.gz"
    version = "21.0.5"

    [[metadata.dependencies.licenses]]
      type = "GraalVM Free Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/graal-free-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:23.0.2:*:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "Oracle GraalVM"
    purl = "pkg:generic/graalvm-jdk@23.0.2?arch=amd64"
    sha256 = "db09b1fe18b83f338af9b3291443774b3170d9eba17538ce2ee39c5e6d601dfc"
    stacks = ["*"]
    uri = "https://download.oracle.com/graalvm/23/archive/graalvm-jdk-23.0.2_linux-x64_bin.tar.gz"
    version = "23.0.2"

    [[metadata.dependencies.licenses]]
      type = "GraalVM Free Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/graal-free-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.6:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Oracle JDK"
    purl = "pkg:generic/oracle-jdk@21.0.6?arch=arm64"
    sha256 = "6f425b302dfc2b4f38d9bdcf5d62656032afdf7795796f4edff082b9e8e8d7d7"
    stacks = ["*"]
    uri = "https://download.oracle.com/java/21/archive/jdk-21.0.6_linux-aarch64_bin.tar.gz"
    version = "21.0.6"

    [[metadata.dependencies.licenses]]
      type = "Oracle No-Fee Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/no-fee-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:23.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Oracle JDK"
    purl = "pkg:generic/oracle-jdk@23.0.2?arch=arm64"
    sha256 = "3f8423bbd538e7cb20a26f944429170b47413af00ccc0e01ce5255f3f9a8d69b"
    stacks = ["*"]
    uri = "https://download.oracle.com/java/23/archive/jdk-23.0.2_linux-aarch64_bin.tar.gz"
    version = "23.0.2"

    [[metadata.dependencies.licenses]]
      type = "Oracle No-Fee Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/no-fee-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.5:*:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "Oracle GraalVM"
    purl = "pkg:generic/graalvm-jdk@21.0.5?arch=arm64"
    sha256 = "3ad68fbb2d13da528dfa0aea9e9345383245ec9c31094dce3905cefba9aac01e"
    stacks = ["*"]
    uri = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.5_linux-aarch64_bin.tar.gz"
    version = "21.0.5"

    [[metadata.dependencies.licenses]]
      type = "GraalVM Free Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/graal-free-license.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:23.0.1:*:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "Oracle GraalVM"
    purl = "pkg:generic/graalvm-jdk@23.0.1?arch=arm64"
    sha256 = "1835a98b87c439c8c654d97956c22d409855952e5560a8127f56c50f3f919d7d"
    stacks = ["*"]
    uri = "https://download.oracle.com/graalvm/23/archive/graalvm-jdk-23.0.1_linux-aarch64_bin.tar.gz"
    version = "23.0.1"

    [[metadata.dependencies.licenses]]
      type = "GraalVM Free Terms and Conditions License"
      uri = "https://www.oracle.com/downloads/licenses/graal-free-license.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
